window.GAME_TRANSLATIONS = [
['Guess the F1 Driver','Adiviná el piloto de F1'],['F1 Driver Guess','Adiviná el piloto de F1'],
['Seasons','Temporadas'],['Stat mode','Estadísticas'],['All','Todas'],['Game mode','Modo de juego'],['Random','Aleatorio'],['Guesses','Intentos'],
["Type a driver's name...",'Escribí el nombre de un piloto...'],['Driver','Piloto'],['First year','Primer año'],['Last year','Último año'],['Titles','Títulos'],['Wins','Victorias'],['Podiums','Podios'],['Points','Puntos'],['Poles','Poles'],['GPs','GPs'],
['Congratulations!','¡Felicitaciones!'],['You guessed the correct driver!','¡Adivinaste el piloto!'],['Play Again','Jugar de nuevo'],
['Choose a driver. ▲ means the answer has a higher value; ▼ means lower. A white cell with ✓ is an exact match. Keep guessing until you find the driver.','Elegí un piloto. ▲ indica que la respuesta tiene un valor mayor; ▼, uno menor. Una casilla blanca con ✓ indica un valor exacto. Seguí hasta encontrar al piloto.'],
['F1 Driver Wins','Victorias de pilotos de F1'],['F1 Higher or Lower','F1: más o menos'],['Click the one with more wins','Elegí al piloto con más victorias'],['Click the one with more raced GPs','Elegí al piloto con más GP disputados'],['Score:','Puntos:'],['Score','Puntos'],['High Score:','Récord:'],['Driver 1','Piloto 1'],['Driver 2','Piloto 2'],['has','tiene'],['race wins','victorias'],['raced GPs','GP disputados'],['Game Over','Fin de la partida'],['Game Over!','¡Fin de la partida!'],['You scored:','Tu puntuación:'],['Back to Menu','Volver al menú'],['Share Score','Compartir puntuación'],['Select Game Mode','Elegí el modo de juego'],['By Race Wins','Por victorias'],['By Raced GPs','Por GP disputados'],['Score copied to clipboard!','¡Puntuación copiada!'],['Failed to copy score.','No se pudo copiar la puntuación.'],['I scored {0} on F1 Higher or Lower! Can you beat my score?','¡Conseguí {0} puntos en F1: más o menos! ¿Podés superarme?'],
['Loading...','Cargando...'],['Unable to load the game. Please try again.','No se pudo cargar el juego. Volvé a intentarlo.'],['Photo unavailable','Foto no disponible'],['Choose either driver when their totals are equal.','Si los valores son iguales, cualquiera de los dos pilotos es válido.'],
['F1 Circuit Guesser','Adiviná el circuito de F1'],['F1 CIRCUIT GUESSER','ADIVINÁ EL CIRCUITO DE F1'],['Test your knowledge of Formula 1 track layouts.','Poné a prueba cuánto conocés los circuitos de Fórmula 1.'],['EASY MODE','MODO FÁCIL'],['HARD MODE','MODO DIFÍCIL'],['3 CORNERS MODE','MODO 3 CURVAS'],['Select the correct circuit from 4 options.','Elegí el circuito correcto entre 4 opciones.'],['Type the correct circuit name.','Escribí el nombre del circuito.'],['Guess the circuit from just 3 corners.','Adiviná el circuito viendo solo 3 curvas.'],['← Back','← Volver'],['Type circuit name...','Escribí el nombre del circuito...'],['Guess','Responder'],['Aliases allowed (e.g., "Spa", "Monza")','Se aceptan nombres cortos (por ejemplo, "Spa", "Monza")'],['Correct!','¡Correcto!'],['Next Circuit','Siguiente circuito'],['Circuits data not loaded yet.','Los circuitos todavía no se cargaron.'],['Error loading circuit.','No se pudo cargar el circuito.'],["You guessed it right. It's",'Acertaste. Es'],['The correct answer was','La respuesta correcta era'],['Final Streak:','Racha final:'],
['F1 Bingo Matrix','Bingo de F1'],['Failed Cells:','Casillas perdidas:'],['Search for an F1 Driver...','Buscá un piloto de F1...'],['Cancel','Cancelar'],['You Win!','¡Ganaste!'],['Raced in {0}','Compitió en {0}'],['Championship in the same year as {0}','Compitió en un campeonato el mismo año que {0}'],['Won a Race','Ganó una carrera'],['Scored a Podium','Consiguió un podio'],['Scored a Point','Consiguió puntos'],['World Champion','Campeón mundial'],['Pole Position','Pole position'],['Fastest Lap','Vuelta rápida'],
['Pick a cell and name a driver who meets both its row and column. Use each driver once. Three mistakes reveal a cell; three lost cells end the game.','Elegí una casilla y un piloto que cumpla ambas condiciones, fila y columna. Usá cada piloto una sola vez. Tres errores revelan una casilla; tres casillas perdidas terminan la partida.'],
['British','Británico'],['German','Alemán'],['French','Francés'],['Italian','Italiano'],['Brazilian','Brasileño'],['Argentine','Argentino'],['Argentinian','Argentino'],['American','Estadounidense'],['Australian','Australiano'],['Austrian','Austríaco'],['Belgian','Belga'],['Canadian','Canadiense'],['Dutch','Neerlandés'],['Finnish','Finlandés'],['Japanese','Japonés'],['Mexican','Mexicano'],['New Zealander','Neozelandés'],['South African','Sudafricano'],['Spanish','Español'],['Swedish','Sueco'],['Swiss','Suizo'],['Portuguese','Portugués'],['Russian','Ruso'],['Danish','Danés'],['Indian','Indio'],['Rhodesian','Rodesiano'],['Venezuelan','Venezolano'],['Colombian','Colombiano'],['Chilean','Chileno'],['Uruguayan','Uruguayo'],['Thai','Tailandés'],['Irish','Irlandés'],
['Predestinato Extras','Minijuegos de Predestinato'],['Back to Main Hub','Volver al inicio'],['Aim Trainer','Práctica de puntería'],['Click the targets before they shrink to nothing.','Tocá los blancos antes de que se achiquen y desaparezcan.'],['Start Game','Comenzar'],['Final Score:','Puntuación final:'],['Level:','Nivel:'],['Lives:','Vidas:'],['Lives','Vidas'],['MISS','ERROR'],['Miss!','¡Error!'],['Dodge Game','Esquivá el tráfico'],['Side-Stepping Dodge Game','Esquivá el tráfico'],['Use Left/Right arrows or tap to move','Usá las flechas izquierda/derecha o tocá para moverte'],['Try Again','Reintentar'],['Falling Objects','Objetos que caen'],['Your Score:','Tu puntuación:'],['Use','Usá'],['Mouse','el mouse'],['or','o'],['Left/Right Arrows','las flechas izquierda/derecha'],['to move.','para moverte.'],['Grid Clicker','Reflejos en la cuadrícula'],['Stroop Effect Test','Prueba del efecto Stroop'],['The Stroop Effect Test','Prueba del efecto Stroop'],['Click the button that matches the','Elegí el botón que coincida con el'],['COLOR','COLOR'],['of the text, not the word itself!','de la tinta, ¡no con la palabra escrita!'],['Time:','Tiempo:'],['Ready?','¿Listo?'],['Red','Rojo'],['Blue','Azul'],['Green','Verde'],['Yellow','Amarillo'],['Orange','Naranja'],['Purple','Violeta'],['You ran out of time!','¡Se terminó el tiempo!'],['Wrong! The font color was {0}.','¡Incorrecto! El color de la tinta era {0}.'],['Four-in-line','Cuatro en línea'],['Four In Line','Cuatro en línea'],["Player {0}'s Turn",'Turno del jugador {0}'],['Player {0} Wins!','¡Ganó el jugador {0}!'],["It's a Draw!",'¡Empate!'],['Score: {0}','Puntos: {0}'],
['Enduro Game','Carrera Enduro'],['🏎 Maximum Speed','🏎 Velocidad Máxima'],['Passed','Pasados'],['Time','Tiempo'],['Crashes','Choques'],['Speed','Velocidad'],['Ready to race!','¡Listo para correr!'],['Pass','Pasá'],['15 cars','15 autos'],['in','en'],['1:30 minutes','1:30 minutos'],['Use','Usá'],['to move.','para moverte.'],['Touch: swipe your finger','Touch: deslizá el dedo'],['START','ARRANCAR'],['🏆 YOU WON!','🏆 ¡GANASTE!'],['You passed all 15 cars.','Pasaste los 15 autos.'],['PLAY AGAIN','JUGAR DE NUEVO'],['⏱ TIME UP!','⏱ TIEMPO!'],['You did not pass all the cars.','No llegaste a pasar todos los autos.'],['TRY AGAIN','INTENTAR DE NUEVO'],['CAR DESTROYED','AUTO DESTRUIDO'],['You crashed','Chocaste'],['3 times','3 veces'],['The car could not take any more.','El auto no aguantó más.'],['left','izq'],['brake','frenar'],['accel.','acel.'],['right','der'],['You passed {0} of {1} cars','Pasaste {0} de {1} autos']
];
window.GAME_TRANSLATIONS.push(
['F1 Bingo Generator','Bingo de F1'],['F1 Higher Lower','F1: más o menos'],['Arcade Games (Predestinato Extras)','Juegos arcade (extras de Predestinato)'],['Maximum Speed – Minigame','Velocidad Máxima – Minijuego'],
['United Kingdom','Reino Unido'],['Germany','Alemania'],['France','Francia'],['Italy','Italia'],['Brazil','Brasil'],['Argentina','Argentina'],['United States','Estados Unidos'],['United States of America','Estados Unidos'],['Australia','Australia'],['Austria','Austria'],['Belgium','Bélgica'],['Canada','Canadá'],['Netherlands','Países Bajos'],['Finland','Finlandia'],['Japan','Japón'],['Mexico','México'],['New Zealand','Nueva Zelanda'],['South Africa','Sudáfrica'],['Spain','España'],['Sweden','Suecia'],['Switzerland','Suiza'],['Russia','Rusia'],['Denmark','Dinamarca'],['India','India'],['Rhodesia','Rodesia'],['Venezuela','Venezuela'],['Chile','Chile'],['Ireland','Irlanda'],['Thailand','Tailandia'],['Portugal','Portugal'],['Colombia','Colombia'],['Monaco','Mónaco'],['China','China'],['Malaysia','Malasia'],['Hungary','Hungría'],['Poland','Polonia'],['Indonesia','Indonesia'],['Czech Republic','República Checa'],['East Germany','Alemania Oriental'],['Liechtenstein','Liechtenstein'],
['Choose left driver','Elegir piloto de la izquierda'],['Choose right driver','Elegir piloto de la derecha'],
['Go around the cars to pass them.','Rodeá a los autos para pasarlos.'],['Crashing slows you down — that car does not count.','Chocar te frena — no te cuenta el auto.'],['Time: {0}','Tiempo: {0}'],
['Missed!','¡Fallaste!'],['Wrong target!','¡Blanco incorrecto!'],['Too slow!','¡Demasiado lento!'],['Draw!','¡Empate!'],
['F1 Telemetry Games','Juegos de F1 Telemetry'],['Guess the Driver','Adiviná el piloto'],['Circuit Guesser','Adiviná el circuito'],['Higher or Lower','Más o menos'],['Play','Jugar']
);
window.GAME_TRANSLATIONS.push(['Failed to load driver data.','No se pudieron cargar los datos de pilotos.'],['Try again','Intentar de nuevo']);
window.GAME_TRANSLATIONS.push(['Driver name','Nombre del piloto'],['Drop a piece in column {0}','Soltar una ficha en la columna {0}'],['Two players share this board. Player 1 is red; Player 2 is white. Choose a column to drop a piece. Connect four horizontally, vertically or diagonally to win.','Dos personas comparten este tablero. El jugador 1 usa rojo; el jugador 2, blanco. Elegí una columna para soltar una ficha. Conectá cuatro en horizontal, vertical o diagonal para ganar.']);
window.GAME_TRANSLATIONS.push(['Shared a season with {0}','Compartió temporada con {0}'],['Choose row {0}, column {1}','Elegir fila {0}, columna {1}']);
window.GAME_TRANSLATIONS.push(['{0} — Photo unavailable','{0} — Foto no disponible']);
